- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest
  - name: upgrade java 8
    ansible.builtin.yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Download tomcat 9
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.78/bin/apache-tomcat-9.0.78.tar.gz
      dest: /opt
      mode: '777'
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /opt/apache-tomcat-9.0.78.tar.gz
      dest: /opt
      remote_src: yes
      